### ISSUE TITLE
Hackage still has bytestring upper-bound

### ISSUE THREAD

**Issue by Ptival** [batterseapower/charsetdetect#1]
Is this fixable?

**Comment by batterseapower** [comment]
Looks like someone forked this at some point and released their own version on Hackage: https://github.com/aelve/charsetdetect-ae / https://hackage.haskell.org/package/charsetdetect-ae. You could use that.

Just in case this is tricky for some reason, I've ported the changes from that branch back to this one and released it on Hackage: https://hackage.haskell.org/package/charsetdetect
